"""Add adviser assignment to students

Revision ID: 1acb57a3b45e
Revises: 
Create Date: 2026-09-11 19:25:03.383406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acb57a3b45e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adviser_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['adviser_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('adviser_id')

    # ### end Alembic commands ###
