"""Add certificate image path

Revision ID: 1f3eef828ed5
Revises: 75070866783b
Create Date: 2026-09-22 16:45:51.884429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3eef828ed5'
down_revision = '75070866783b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('certificate_image_path')

    # ### end Alembic commands ###
