"""Add internship applications

Revision ID: 406ad6bf784d
Revises: c9f91d59b913
Create Date: 2026-09-15 13:46:30.832502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406ad6bf784d'
down_revision = 'c9f91d59b913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['industry_partners.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internship_applications')
    # ### end Alembic commands ###
