"""Add account approval status

Revision ID: 626da4fb7539
Revises: 1acb57a3b45e
Create Date: 2026-09-11 21:17:28.709525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '626da4fb7539'
down_revision = '1acb57a3b45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=False))
        batch_op.alter_column('is_active_account',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active_account',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
