"""add student profile picture fields

Revision ID: 97bb3ff02b3b
Revises: 2ecc3898e899
Create Date: 2026-10-09 17:55:49.736079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bb3ff02b3b'
down_revision = '2ecc3898e899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pending_profile_picture_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_rejection_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_rejection_reason')
        batch_op.drop_column('profile_picture_status')
        batch_op.drop_column('pending_profile_picture_path')
        batch_op.drop_column('profile_picture_path')

    # ### end Alembic commands ###
