"""Add verification document fields

Revision ID: c9f91d59b913
Revises: 626da4fb7539
Create Date: 2026-09-11 21:34:52.514395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f91d59b913'
down_revision = '626da4fb7539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_document_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_document_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_document_type')
        batch_op.drop_column('verification_document_path')

    # ### end Alembic commands ###
